// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutParallaxHighlight from "@/components/sections/about/AboutParallaxHighlight";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
              <AboutParallaxHighlight
        textAnimation="slide-up"
        tag="Meet Jenny Mejia"
        title="Crafting Unforgettable"
        titleHighlight="Floral Memories"
        description="Owned and lovingly crafted by Jenny Mejia in Amityville, Long Island. We specialize in custom floral arrangements, eternal roses, real rose bouquets, romantic gifts, themed floral creations, and event decor. Spanish-speaking customers are always welcome!"
        primaryButton={{"text":"Message Jenny on Instagram","href":"https://instagram.com/mejia_eternalflowers_decor"}}
        secondaryButton={{"href":"#collection","text":"Browse Gallery"}}
        backImageSrc="https://storage.googleapis.com/webild/users/user_3JEfDWBEyWTUPaI8slU4nHApWGT/uploaded-1791197913892-mc6i91ka.jpg"
        frontImageSrc="https://storage.googleapis.com/webild/users/user_3JEfDWBEyWTUPaI8slU4nHApWGT/uploaded-1791197913894-v2wp6euy.jpg"
      />
            </div>
  );
}
