// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "collection" section.

import React from 'react';
import ProductVariantCardsHighlight from "@/components/sections/product/ProductVariantCardsHighlight";

export default function CollectionSection(): React.JSX.Element {
  return (
    <div id="collection" data-section="collection">
              <ProductVariantCardsHighlight
        textAnimation="slide-up"
        tag="Our Work"
        title="Signature Floral"
        titleHighlight="& Decor Creations"
        description="Each bouquet and decor arrangement is hand-crafted to order for Valentine’s Day, birthdays, proposals, anniversaries, quinceañeras, and special events."
        primaryButton={{"href":"https://instagram.com/mejia_eternalflowers_decor","text":"Order Custom Bouquet"}}
        secondaryButton={{"text":"Order FAQ","href":"#faq"}}
        products={[{"price":"Custom Order","imageSrc":"https://storage.googleapis.com/webild/users/user_3JEfDWBEyWTUPaI8slU4nHApWGT/uploaded-1791197913894-pyfkplt4.jpg","variant":"Pink Roses • Gold Butterflies","name":"Golden Butterfly Bouquet"},{"imageSrc":"https://storage.googleapis.com/webild/users/user_3JEfDWBEyWTUPaI8slU4nHApWGT/uploaded-1791197913894-v2wp6euy.jpg","price":"Custom Order","variant":"Theme Decor • Satin Roses","name":"Fairytale Character Crown Bouquet"},{"price":"Custom Order","variant":"Real White Roses • Luxe Wrapping","name":"Luxury Pure White Rose Bouquet","imageSrc":"https://storage.googleapis.com/webild/users/user_3JEfDWBEyWTUPaI8slU4nHApWGT/uploaded-1791197913893-l9pp8c0i.jpg"},{"variant":"Real Blush Pink Roses","name":"Blush Signature Rose Bouquet","imageSrc":"https://storage.googleapis.com/webild/users/user_3JEfDWBEyWTUPaI8slU4nHApWGT/uploaded-1791197913894-hajbgwlz.jpg","price":"Custom Order"}]}
      />
            </div>
  );
}
