// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqSimpleHighlight from "@/components/sections/faq/FaqSimpleHighlight";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
              <FaqSimpleHighlight
        textAnimation="slide-up"
        tag="FAQ"
        title="Frequently Asked"
        titleHighlight="Questions"
        description="Everything you need to know about the world's most universal chair."
        items={[{"answer":"We are based in Amityville, NY and proudly serve customers across Long Island and surrounding areas.","question":"Where are you located and what areas do you serve?"},{"answer":"You can place an order directly by sending a Direct Message to our Instagram account @mejia_eternalflowers_decor or clicking any \"Order on Instagram\" button on this website!","question":"How do I place a custom order?"},{"answer":"¡Sí, claro! Atendemos a nuestros clientes tanto en español como en inglés con mucho gusto.","question":"¿Atienden en español?"},{"question":"What occasions do you create arrangements for?","answer":"We craft custom arrangements for Valentine’s Day, birthdays, romantic proposals, anniversaries, quinceañeras, baby showers, themed parties, and special events."},{"answer":"We specialize in both real fresh rose bouquets and long-lasting eternal rose arrangements, customized with butterflies, crowns, custom ribbons, and themed accessories.","question":"Do you offer eternal roses as well as fresh flowers?"}]}
      />
            </div>
  );
}
