// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroOverlayParallax from "@/components/sections/hero/HeroOverlayParallax";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
              <HeroOverlayParallax
        imageSrc="https://storage.googleapis.com/webild/users/user_3JEfDWBEyWTUPaI8slU4nHApWGT/uploaded-1791197913894-pyfkplt4.jpg"
        avatarsLabel="Handcrafted with love in Long Island, NY by Jenny Mejia. ¡Hablamos Español!"
        avatarsSrc={["https://storage.googleapis.com/webild/users/user_3JEfDWBEyWTUPaI8slU4nHApWGT/uploaded-1791197913892-mc6i91ka.jpg","https://storage.googleapis.com/webild/users/user_3JEfDWBEyWTUPaI8slU4nHApWGT/uploaded-1791197913893-l9pp8c0i.jpg","https://storage.googleapis.com/webild/users/user_3JEfDWBEyWTUPaI8slU4nHApWGT/uploaded-1791197913894-hajbgwlz.jpg"]}
        title="Custom Floral Arrangements"
        titleHighlight="& Eternal Roses"
        primaryButton={{"text":"Order on Instagram","href":"https://instagram.com/mejia_eternalflowers_decor"}}
        secondaryButton={{"href":"#collection","text":"View Arrangements"}}
      />
            </div>
  );
}
