// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialDetailedCardsHighlight from "@/components/sections/testimonial/TestimonialDetailedCardsHighlight";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
              <TestimonialDetailedCardsHighlight
        textAnimation="slide-up"
        tag="Client Love"
        title="Words From Our"
        titleHighlight="Delighted Clients"
        description="Here is what our happy customers in Long Island and beyond have to say about Jenny's arrangements."
        testimonials={[{"quote":"The butterfly pink rose bouquet Jenny made for my sister's birthday was absolutely breathtaking! Everyone at the party couldn't stop taking pictures.","title":"Most beautiful bouquet ever!","role":"Long Island, NY","name":"Sofia M.","imageSrc":"https://storage.googleapis.com/webild/users/user_3JEfDWBEyWTUPaI8slU4nHApWGT/uploaded-1791197913894-pyfkplt4.jpg"},{"quote":"¡Excelente servicio y un trabajo hermoso! Order a themed arrangement for a quinceañera and Jenny exceeded all my expectations. Highly recommended!","title":"¡Increíble trabajo y atención!","imageSrc":"https://storage.googleapis.com/webild/users/user_3JEfDWBEyWTUPaI8slU4nHApWGT/uploaded-1791197913894-v2wp6euy.jpg","role":"Amityville, NY","name":"Isabella G."},{"quote":"Ordered a surprise luxury rose bouquet for our anniversary. The quality of the roses and the elegant wrapping made it so special.","title":"Perfect anniversary surprise","imageSrc":"https://storage.googleapis.com/webild/users/user_3JEfDWBEyWTUPaI8slU4nHApWGT/uploaded-1791197913893-l9pp8c0i.jpg","name":"Carlos R.","role":"Long Island, NY"}]}
      />
            </div>
  );
}
